### ISSUE TITLE
ERROR! Not logged on.

### ISSUE THREAD

**Issue by AndyLee1024** [jens1101/SteamCMD-JS-Interface#11]
Hi developer.

When i use workshop_download_item commands to download workshop item. i got an error : ERROR! Not logged on.

![image](https://user-images.githubusercontent.com/3479173/78322209-a879e780-75a0-11ea-99b3-35d6491b8523.png)

**Comment by jens1101** [comment]
Thanks for reporting this issue. You unfortunately can't log in via the `init` function. You need to use the `login` function after SteamCmd has initialised. If you have Steam Guard activated then you will also need a Steam Guard code.

Here is example code of what I mean:
```js
const steamCmd = await SteamCmd.init()

// Now open your Steam app on your mobile phone and get a Steam Guard code.
// I will use 'AABB2' in this example.

await steamCmd.login('username', 'password123', 'AABB2')
console.log(await steamCmd.isLoggedIn()) // Logs "true"
```

Note that you only have to do this once. After you ran the above code once you can now just run this in the future:
```js
const steamCmd = await SteamCmd.init({
  username: 'username'
})
console.log(await steamCmd.isLoggedIn()) // Logs "true"
```

**Comment by jens1101** [comment]
@AndyLee1024 I just tested out this issue and I also got a login issue. My above comment is incorrect!

To currently solve this issue you need to manually append the login command to your array of commands. For example:
```js
const steamCmd = await SteamCmd.init({
  username: 'username'
})

const commands = [
  'login username',
  'workshop_download_item 255710 445589127'
]

for await (const line of steamCmd.run(commands)) {
  console.log(line)
}
```

I am currently working on improving this in the next release so that the run command logs you in automatically.
